/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:bafc2db6-e2aa-4e75-be60-4105fe45dfba",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_WD2Ew8zY4",
    "aws_user_pools_web_client_id": "18kkav5rhusb04vivrkighi919",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bmaidkhw35c55gidrb5j4nfvie.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_user_files_s3_bucket": "metro12184b595928421593bf774d69c36c9b143104-devmetro",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_content_delivery_bucket": "metro-20210909145812-hostingbucket-devmetro",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://metro-20210909145812-hostingbucket-devmetro.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
